package com.gianlucaveschi.daggercourse.di;

import com.gianlucaveschi.daggercourse.di.authComponent.AuthModule;
import com.gianlucaveschi.daggercourse.di.authComponent.AuthScope;
import com.gianlucaveschi.daggercourse.di.authComponent.AuthViewModelsModule;
import com.gianlucaveschi.daggercourse.di.mainComponent.MainFragmentBuildersModule;
import com.gianlucaveschi.daggercourse.di.mainComponent.MainModule;
import com.gianlucaveschi.daggercourse.di.mainComponent.MainScope;
import com.gianlucaveschi.daggercourse.di.mainComponent.MainViewModelsModule;
import com.gianlucaveschi.daggercourse.ui.auth.AuthActivity;
import com.gianlucaveschi.daggercourse.ui.main.MainActivity;

import dagger.Module;
import dagger.android.ContributesAndroidInjector;

@Module
public abstract class ActivityBuildersModule {

    /**Subcomponents are generated by the @ContributesAndroidInjector
     * and can only be seen in the code generated by Dagger.
     *
     * Look Inside :
     * */

    @AuthScope //The AuthSubComponent now owns the AuthScope
    @ContributesAndroidInjector(
            modules = {
                    AuthViewModelsModule.class,
                    AuthModule.class
            })
    abstract AuthActivity contributeAuthActivity(); //generates the SubComponent

    @MainScope //The MainSubComponent now owns the MainScope
    @ContributesAndroidInjector(
            modules  = {
                    MainFragmentBuildersModule.class,
                    MainViewModelsModule.class,
                    MainModule.class
            })
    abstract MainActivity contributeMainActivity(); //Generates the SubComponent
}
